config/routes.rb
DownloadMyScore::Application.routes.draw do

  root 'students#index'
  post 'students/login'
  get 'students/download'
  get 'students/login_success'
  get 'students/login_failed'
  get 'students/logout'

end

app/models/student.rb
class Student < ActiveRecord::Base


    validates :no, :presence => true, :uniqueness => {:case_sensitive => false}
    validates :password, :confirmation => true


    def self.authenticate no, password
        student = find_by_no no
        if student && student.pid == password
            student
        else
            false
        end
    end

    # 如果需要編碼，詳細請見 
    # http://webdevrefinery.com/forums/topic/9724-ruby-on-rails-user-authentication/
    
    def encrypt_password
        if password.present?
            self.salt = BCrypt::Engine.generate_salt
            self.password = BCrypt::Engine.hash_secret password, salt
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

   def index 
   end

   def login
      student = Student.authenticate params[:no], params[:password]

      if student
         session[:student_name]=student.name
         session[:student_pid]=student.pid
         redirect_to :action=>'login_success'
      else
         flash[:notice]="請輸入正確帳號密碼！"
         render :action=>'login_failed'
      end

   end

   def login_success
      @student_name=session[:student_name]
   end

   def login_failed
   end

   def download
      @file = '/home/taichis/DownloadMyScore/scores/' + session[:student_pid] + ".pdf"
      send_file @file, :type=>"application/pdf", :x_sendfile=>true
   end

   def logout
      session[:student_pid]=nil
      session[:student_name]=nil
      redirect_to root_url
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-TW">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>正心高三學生下載成績證明</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->


  </body>
</html>

app/views/students/index.html.erb
     <%= form_tag 'students/login',class:'form-signin',role:'form' do %>
        <h2 class="form-signin-heading">請登入</h2>
        <%= text_field_tag 'no', nil, placeholder:'請輸入學號', class:'form-control',required:true,autofocus:true %>
        <br />
        <%= password_field_tag 'password', nil, placeholder:'請輸入身分證字號', class:'form-control',required:true %>
        <br />
        </label>
        <%= submit_tag "登入", class:'btn btn-lg btn-primary btn-block' %>
     <% end %>

app/views/students/login_failed.html.erb
<h1> 登入失敗 </h1>

app/views/students/login_success.html.erb
<h1> <%= @student_name %> 登入成功 </h1>

<br />

<%= link_to "下載成績單檔案", students_download_path, :class=>"btn btn-primary" %>
<%= link_to "登出", students_logout_path, :class=>"btn btn-danger" %>